---
downloads: ~/.ansible-downloads/
repo-location: ~/Development/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: yes
configure_osx: yes
configure_vscode: yes
configure_dock: yes
osx_use_dotfile: no
osx_use_defaults: yes
clone_repos: yes

dotfiles_repo: https://github.com/fishd72/Dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "{{ repo=location }}/Dotfiles"
dotfiles_files:
  - .zshrc
  - .aliases
  - .gitignore
  - .gitconfig
  - .inputrc
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - httpie
  - mas
  - packer
  - qemu
  - http://git.io/sshpass.rb
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcleaner
  - autodmg
  - balenaetcher
  - caffeine
  - cheatsheet
  - coconutbattery
  - cyberduck
  - Dosbox
  - evernote
  - firefox
  - handbrake
#  - homebrew/cask-drivers/synology-drive
  - launchcontrol
  - Microsoft-teams
  - OpenEmu
  - ripit
  - Signal
  - slack
  - Steam
  - suspicious-package
  - transmission
  - twitch
  - vagrant
  - visual-studio-code
  - vmware-fusion
  - Vuescan
  - 1password


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
- { id: 1037126344, name: "Apple Configurator 2 (2.12.1)" }
- { id: 411643860, name: "DaisyDisk (4.10)" }
- { id: 425264550, name: "Disk Speed Test (3.2)" }
- { id: 1481669779, name: "Evernote Web Clipper (1.0.5)" }
- { id: 1175706108, name: "Geekbench 4 (4.4.1)" }
- { id: 731062389, name: "iFlicks 2 (2.8.1)" }
- { id: 409183694, name: "Keynote (10.0)" }
- { id: 1295203466, name: "Microsoft Remote Desktop (10.3.9)" }
- { id: 1289197285, name: "MindNode (7.1.1)" }
- { id: 409203825, name: "Numbers (10.0)" }
- { id: 409201541, name: "Pages (10.0)" }
- { id: 451907568, name: "Paprika Recipe Manager (2.2.0)" }
- { id: 1160374471, name: "PiPifier (1.2.4)" }
- { id: 407963104, name: "Pixelmator (3.9)" }
- { id: 425424353, name: "The Unarchiver (4.2.1)" }
- { id: 1278508951, name: "Trello (2.11.4)" }
- { id: 1384080005, name: "Tweetbot (3.3.3)" }
- { id: 494803304, name: "WiFi Explorer (2.6)" }
mas_email: ""
mas_password: ""


osx_script: "~/.osx --no-restart"
osx_defaults: 
# Expand save panel by default
- { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true }
# Expand print panel by default
- { domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint, type: bool, value: true }
# Automatically quit printer app once the print jobs complete
- { domain: com.apple.print.PrintingPrefs, key: "Quit When Finished", type: bool, value: true }
# Disable smart quotes as they’re annoying when typing code
- { domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false }
# Disable smart dashes as they’re annoying when typing code
- { domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false }
# Trackpad: map bottom right corner to right-click
- { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadCornerSecondaryClick, type: int, value: 0 }
- { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadRightClick, type: bool, value: true }
- { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadThreeFingerHorizSwipeGesture, type: int, value: 2 }
- { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadThreeFingerTapGesture, type: int, value: 0 }
- { domain: NSGlobalDocom.apple.driver.AppleBluetoothMultitouch.trackpadmain, key: TrackpadThreeFingerVertSwipeGesture, type: int, value: 2 }
- { domain: NSGlobalDomain, key: com.apple.trackpad.enableSecondaryClick, type: bool, value: true }
# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs - 0 = text boxes and lists, 2/3 = all controls)
- { domain: NSGlobalDomain, key: AppleKeyboardUIMode, type: int, value: 0 }
# Set a blazingly fast keyboard repeat rate, and make it happen more quickly.
- { domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 20 }
- { domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 1 }
# Disable auto-correct
- { domain: NSGlobalDomain, key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false }
# Require password immediately after sleep or screen saver begins
- { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
- { domain: com.apple.screensaver, key: askForPasswordDelay, type: int, value: 0 }
# Save screenshots to the desktop
- { domain: com.apple.screencapture, key: location, type: string, value: "${HOME}/Desktop" }
# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
- { domain: com.apple.screencapture, key: type, type: string, value: "png" }
# Disable shadow in screenshots
- { domain: com.apple.screencapture, key: disable-shadow, type: bool, value: true }
# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
- { domain: com.apple.finder, key: NewWindowTarget, type: string, value: "PfDe" }
- { domain: com.apple.finder, key: NewWindowTargetPath, type: string, value: "file://${HOME}/Desktop/" }
# Show icons for hard drives, servers, and removable media on the desktop
- { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
#defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
- { domain: com.apple.finder, key: ShowMountedServersOnDesktop, type: bool, value: true }
- { domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, type: bool, value: true }
# Finder: show all filename extensions
- { domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: true }
# Finder: show status bar
- { domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
# Finder: allow text selection in Quick Look
- { domain: com.apple.finder, key: QLEnableTextSelection, type: bool, value: true }
# Display full POSIX path as Finder window title
- { domain: com.apple.finder, key: _FXShowPosixPathInTitle, type: bool, value: true }
# When performing a search, search the current folder by default
- { domain: com.apple.finder, key: FXDefaultSearchScope, type: string, value: "SCcf" }
# Disable the warning when changing a file extension
- { domain: com.apple.finder, key: FXEnableExtensionChangeWarning, type: bool, value: false }
# Enable spring loading for directories
- { domain: NSGlobalDomain, key: com.apple.springing.enabled, type: bool, value: true }
# Remove the spring loading delay for directories
#defaults write NSGlobalDomain com.apple.springing.delay -float 0.1
#- { domain: NSGlobalDomain, key: com.apple.springing.delay, type: string, value: Dark }   ### FIX THIS !
# Avoid creating .DS_Store files on network volumes
- { domain: com.apple.desktopservices, key: DSDontWriteNetworkStores, type: bool, value: true }
# Automatically open a new Finder window when a volume is mounted
- { domain: com.apple.frameworks.diskimages, key: auto-open-ro-root, type: bool, value: true }
- { domain: com.apple.frameworks.diskimages, key: auto-open-rw-root, type: bool, value: true }
- { domain: com.apple.finder, key: OpenWindowForNewRemovableDisk, type: bool, value: true }
# Set the icon size of Dock items
- { domain: com.apple.dock, key: tilesize, type: int, value: 64 }
# Make Dock icons of hidden applications translucent
- { domain: com.apple.dock, key: showhidden, type: bool, value: true }
# Screen hot corners, possible values:
#  0: no-op; 2: Mission Control; 3: Show application windows; 4: Desktop
#  5: Start screen saver; 6: Disable screen saver; 7: Dashboard
#  10: Put display to sleep; 11: Launchpad; 12: Notification Center
# Bottom right screen corner → Start screen saver
- { domain: com.apple.dock, key: wvous-br-corner, type: int, value: 5 }
- { domain: com.apple.dock, key: wvous-br-modifier, type: int, value: 0 }
# Top right screen corner → Disable screen saver
- { domain: com.apple.dock, key: wvous-tr-corner, type: int, value: 6 }
- { domain: com.apple.dock, key: wvous-tr-modifier, type: int, value: 0 }
# Top left screen corner → Disable screen saver
- { domain: com.apple.dock, key: wvous-tl-corner, type: int, value: 6 }
- { domain: com.apple.dock, key: wvous-tl-modifier, type: int, value: 0 }
# Bottom left screen corner → Put display to sleep
- { domain: com.apple.dock, key: wvous-bl-corner, type: int, value: 10 }
- { domain: com.apple.dock, key: wvous-bl-modifier, type: int, value: 0 }
# Prevent Safari from opening ‘safe’ files automatically after downloading
- { domain: com.apple.Safari, key: AutoOpenSafeDownloads, type: bool, value: false }
# Enable Safari’s debug menu
- { domain: com.apple.Safari, key: IncludeInternalDebugMenu, type: bool, value: true }
# Enable the Develop menu and the Web Inspector in Safari
- { domain: com.apple.Safari, key: IncludeDevelopMenu, type: bool, value: true }
- { domain: com.apple.Safari, key: WebKitDeveloperExtrasEnabledPreferenceKey, type: bool, value: true }
- { domain: com.apple.Safari, key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled, type: bool, value: true }
# Add a context menu item for showing the Web Inspector in web views
- { domain: NSGlobalDomain, key: WebKitDeveloperExtras, type: bool, value: true }
# Disable send and reply animations in Mail.app
- { domain: com.apple.mail, key: DisableReplyAnimations, type: bool, value: true }
- { domain: com.apple.mail, key: DisableSendAnimations, type: bool, value: true }
# Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
- { domain: com.apple.mail, key: AddressesIncludeNameOnPasteboard, type: bool, value: false }
# Show the main window when launching Activity Monitor
- { domain: com.apple.ActivityMonitor, key: OpenMainWindow, type: bool, value: true }
# Show all processes in Activity Monitor
- { domain: com.apple.ActivityMonitor, key: ShowCategory, type: int, value: 0 }
# Use plain text mode for new TextEdit documents
- { domain: com.apple.TextEdit, key: RichText, type: int, value: 0 }
# Open and save files as UTF-8 in TextEdit
- { domain: com.apple.TextEdit, key: PlainTextEncoding, type: int, value: 4 }
- { domain: com.apple.TextEdit, key: PlainTextEncodingForWrite, type: int, value: 4 }
# Use `~/Documents/Torrents` to store incomplete downloads
- { domain: org.m0k.transmission, key: UseIncompleteDownloadFolder, type: bool, value: true }
- { domain: org.m0k.transmission, key: IncompleteDownloadFolder, type: string, value: "${HOME}/Documents/Torrents" }
# Use `~/Downloads` to store completed downloads
- { domain: org.m0k.transmission, key: DownloadLocationConstant, type: bool, value: true }
# Don’t prompt for confirmation before downloading
- { domain: org.m0k.transmission, key: DownloadAsk, type: bool, value: false }
- { domain: org.m0k.transmission, key: MagnetOpenAsk, type: bool, value: false }
# Don’t prompt for confirmation before removing non-downloading active transfers
- { domain: org.m0k.transmission, key: CheckRemoveDownloading, type: bool, value: true }
# Trash original torrent files
- { domain: org.m0k.transmission, key: DeleteOriginalTorrent, type: bool, value: true }
# Hide the donate message
- { domain: org.m0k.transmission, key: WarningDonate, type: bool, value: false }
# Hide the legal disclaimer
- { domain: org.m0k.transmission, key: WarningLegal, type: bool, value: false }
# IP block list.
# Source: https://giuliomac.wordpress.com/2014/02/19/best-blocklist-for-transmission/
- { domain: org.m0k.transmission, key: BlocklistNew, type: bool, value: true }
- { domain: org.m0k.transmission, key: BlocklistURL, type: string, value: "http://john.bitsurge.net/public/biglist.p2p.gz" }
- { domain: org.m0k.transmission, key: BlocklistAutoUpdate, type: bool, value: true }
# Randomize port on launch
- { domain: org.m0k.transmission, key: RandomPort, type: bool, value: true }


vscode_setup_sf_font: true
default_vscode_packages:
  - bbenoist.vagrant
  - DavidAnson.vscode-markdownlint
  - esbenp.prettier-vscode
  - marcostazi.VS-code-vagrantfile
  - mrmlnc.vscode-duplicate
  - ms-python.python
  - vscoss.vscode-ansible


dockitems_disabled:
  - Launchpad
  - Contacts
  - Notes
  - Maps
  - Photos
  - FaceTime
  - Music
  - Podcasts
  - TV
  - News
  - App Store
  
dockitems_enabled:
  - name: Safari
    path: "/System/Applications/Safari.app"
    pos: 1
  - name: Mail
    path: "/System/Applications/Mail.app"
    pos: 2
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 3
  - name: Signal
    path: "/Applications/Signal.app"
    pos: 4
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 5
  - name: Messages
    path: "/System/Applications/Messages.app"
    pos: 6
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 7
  - name: Reminders
    path: "/System/Applications/Reminders.app"
    pos: 8
  - name: System Preferences
    path: "/System/Applications/System Preferences.app"
    pos: 9
  - name: VMware Fusion
    path: "/Applications/VMware Fusion.app"
    pos: 10


git_repos:
   - https://github.com/fishd72/vagrant-ansible.git
   - https://github.com/fishd72/vagrant-jpslab.git
   - https://github.com/fishd72/vagrant-dplab.git
   - https://github.com/agkozak/agkozak-zsh-prompt.git


# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
