---
- name: Ensure git staging area exists.
  file:
    path: "{{ repo-location }}"
    state: directory

- name: Clone listed Git repos.
  git:
    repo: "{{ item.name | default(item) }}"
    dest: "{{ repo-location }}"
  loop: "{{ git_repos }}"
